close all;
clear;
clc;
board = new_board();
gamestate = struct(...
    'WhiteARookMove', false,...
    'BlackARookMove', false,...
    'WhiteHRookMove', false,...
    'BlackHRookMove', false,...
    'WhiteKingMove', false,...
    'BlackKingMove', false,...
    'WhiteEnPassant', false,...
    'BlackEnPassant', false);
draw_board(board, gamestate);